/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.sql.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author SUBHAM
 */
public class employee_infowithtextfield extends javax.swing.JFrame {

        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        
    public employee_infowithtextfield() {
        initComponents();
         conn =javaconect.ConnecrDb();
         update_table();
    }
private void update_table(){
    
    try{
    String sql="select * from employeeinfo";
    pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
    Table_employee.setModel(DbUtils.resultSetToTableModel(rs));
    
    }
    catch(SQLException e)
    {
         JOptionPane.showMessageDialog(null,e);
    }
   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_employee = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_employee.setBackground(new java.awt.Color(204, 204, 255));
        Table_employee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Table_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_employeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Table_employeeMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Table_employee);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1064, 275));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookeh.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 90, 740, 390));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookeh.jpeg"))); // NOI18N
        jLabel2.setText("jLabel1");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -180, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookeh.jpeg"))); // NOI18N
        jLabel3.setText("jLabel1");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, -180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookeh.jpeg"))); // NOI18N
        jLabel4.setText("jLabel1");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 740, 310));

        jLabel6.setText("jLabel6");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        jLabel7.setText("jLabel7");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1137, 430));

        setSize(new java.awt.Dimension(1132, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Table_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_employeeMouseClicked
  
    }//GEN-LAST:event_Table_employeeMouseClicked

    private void Table_employeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_employeeMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_Table_employeeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_employee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
