/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author SUBHAM
 */
public class tabletextdata extends javax.swing.JFrame {

     Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
    /**
     * Creates new form tabletextdata
     */
    public tabletextdata() {
        initComponents();
        conn =javaconect.ConnecrDb();
         update_table();
         Fillcombo();
         Currentdate();
    }
private void update_table(){
    
    try{
    String sql="select * from StudentDetails";
    pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
    Tableemployee.setModel(DbUtils.resultSetToTableModel(rs));
    
    }
    catch(SQLException e)
    {
         JOptionPane.showMessageDialog(null,e);
    }
   
}
private void Fillcombo(){
    try{
       String sql="select * from StudentDetails"; 
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();
           
           while(rs.next())
           {
               String aa=rs.getString("Name");
               ComboBox.addItem(aa);
           }
   }
   catch(SQLException e)
   {
       JOptionPane.showMessageDialog(null,e);
   }
}

public void Currentdate(){
    Calendar cal= new GregorianCalendar();
    int month = cal.get(Calendar.MONTH);
    int date = cal.get(Calendar.DAY_OF_MONTH);
    int year=cal.get(Calendar.YEAR);
    Date_txt.setText(date+"/"+(month+1)+"/"+year);
       
    int sec = cal.get(Calendar.SECOND);
    int min = cal.get(Calendar.MINUTE);
    int hr=cal.get(Calendar.HOUR);
    Time_txt.setText(hr+"::"+(min)+"::"+sec);

}


public void close(){
    WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        maths = new javax.swing.JTextField();
        chemistry = new javax.swing.JTextField();
        ip = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        per = new javax.swing.JTextField();
        physics = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tableemployee = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Date_txt = new javax.swing.JMenu();
        Time_txt = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, -1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, -1));
        jPanel1.add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 100, -1));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, -1));

        id.setToolTipText("");
        id.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 100, -1));
        jPanel1.add(maths, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 70, -1));
        jPanel1.add(chemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 70, -1));
        jPanel1.add(ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 70, -1));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 70, -1));

        per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perActionPerformed(evt);
            }
        });
        jPanel1.add(per, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 70, -1));
        jPanel1.add(physics, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 70, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Surname");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Class");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 50, -1));

        jLabel14.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 255, 153));
        jLabel14.setText("MARKS.....");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 130, -1));

        jLabel15.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Physics");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, -1));

        jLabel16.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Maths");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 80, -1));

        jLabel17.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Chemistry");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 120, -1));

        jLabel18.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("IP");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 20, -1));

        jLabel19.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 80, -1));

        jLabel20.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Percentage");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, -1));

        jLabel21.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Roll NO");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 280, 470));

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button-Close-icon (1).png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 20));

        jLabel1.setFont(new java.awt.Font("VAGRounded BT", 1, 18)); // NOI18N
        jLabel1.setText("Click to display the student data :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, -1));

        ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBoxMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComboBoxMousePressed(evt);
            }
        });
        getContentPane().add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 110, -1));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(153, 0, 153), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 102)));

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(addbtn)
                .addGap(18, 18, 18)
                .addComponent(update)
                .addGap(18, 18, 18)
                .addComponent(delete)
                .addGap(18, 18, 18)
                .addComponent(clear)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 130, 210));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));

        txt_search.setBackground(new java.awt.Color(204, 255, 204));
        txt_search.setToolTipText("Search id,name");
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 140, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/243_-_Male_Student-128.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 120, 140));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        Tableemployee.setBackground(new java.awt.Color(102, 0, 102));
        Tableemployee.setForeground(new java.awt.Color(255, 255, 255));
        Tableemployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tableemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableemployeeMouseClicked(evt);
            }
        });
        Tableemployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableemployeeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tableemployee);

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("List of students :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 750, 380));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        Date_txt.setText("Date");
        jMenuBar1.add(Date_txt);

        Time_txt.setText("Time");
        jMenuBar1.add(Time_txt);

        jMenu3.setText("Help");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Help");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1046, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
        close();      
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
      try
      {
          
          String sql="Insert into StudentDetails(Name,Surname,Class,Physics,Maths,Chemistry,IP,Total,Percentage) values(?,?,?,?,?,?,?,?,?)";
          pst=conn.prepareStatement(sql);
          pst.setString(1,name.getText());
          pst.setString(2,surname.getText());
          pst.setString(3,age.getText());
          pst.setString(4,physics.getText());
              pst.setString(5,maths.getText());
              pst.setString(6,chemistry.getText());
              pst.setString(7,ip.getText());
               
           int p=Integer.parseInt(physics.getText());
           int m=Integer.parseInt(maths.getText());
           int c=Integer.parseInt(chemistry.getText());
           int i=Integer.parseInt(ip.getText());
           float tot;
           float percentage;
           tot=p+m+c+i;
           percentage= tot/4;
           String answer;
           total.setText(String.valueOf(tot));
           answer=String.format("%.2f",percentage);
           per.setText(answer);
             
           pst.setString(8,total.getText());
           pst.setString(9,per.getText());
           pst.execute();
           
           if(percentage>50)
           {
               per.setBackground(Color.GREEN);
               per.setForeground(Color.BLACK);
           }
           else
           {
               per.setBackground(Color.RED);
                per.setForeground(Color.white);
           }
              
      }
      catch(NumberFormatException | SQLException e){
          JOptionPane.showMessageDialog(null,e);
      }
        update_table();
    }//GEN-LAST:event_addbtnActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
               String add1=id.getText();
               String add2= name.getText();
              
               String add3=surname.getText();
               
               String add=age.getText();
               
               String adr1= physics.getText();
              
               String adr2=  maths.getText();
             
               String adr3=chemistry.getText();
               String adr=ip.getText();
                int p=Integer.parseInt(physics.getText());
           int m=Integer.parseInt(maths.getText());
           int c=Integer.parseInt(chemistry.getText());
           int i=Integer.parseInt(ip.getText());
           float tot;
           float percentage;
           tot=p+m+c+i;
           percentage= tot/4;
           String answer;
           total.setText(String.valueOf(tot));
           answer=String.format("%.2f",percentage);
           per.setText(answer);
               
               String sql="update StudentDetails set Name='"+add2+"',Surname='"+add3+"',Class='"+add+"',Physics='"+adr1+"',Maths='"+adr2+"',Chemistry='"+adr3+"',IP='"+adr+"',Total='"+total.getText()+"',Percentage= '"+per.getText()+"' where RollNo='"+add1+"' ";
               pst=conn.prepareStatement(sql);
               pst.execute();
               if(percentage>50)
           {
               per.setBackground(Color.GREEN);
               per.setForeground(Color.BLACK);
           }
           else
           {
               per.setBackground(Color.RED);
                per.setForeground(Color.white);
           }
        }
        catch(NumberFormatException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
         update_table();
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        int p=JOptionPane.showConfirmDialog(null,"Do you really want to delete?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
        String sql="delete from StudentDetails where RollNo=?";
        try{
        
        pst=conn.prepareStatement(sql);
        pst.setString(1,id.getText());
        pst.execute();
         JOptionPane.showMessageDialog(null,"Deleted");
     }
     catch(SQLException e){
         JOptionPane.showMessageDialog(null,e);
     }
        
             update_table();
    }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
         id.setText("");
         name.setText("");
         surname.setText("");
         age.setText("");
         physics.setText("");
         maths.setText("");
         chemistry.setText("");
         ip.setText("");
         total.setText("");
         per.setText("");
         int a=1;
                 if(a==1)
                 {
                     per.setBackground(Color.white);
                     per.setForeground(Color.black);
                 }
         
    }//GEN-LAST:event_clearActionPerformed

    private void ComboBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxMousePressed
        // TODO add your handling code here:
        String tm=(String)ComboBox.getSelectedItem();
        String sql="select * from StudentDetails where Name=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,tm);
            rs=pst.executeQuery();
            if(rs.next())
            {
                
               String add1=rs.getString("RollNo");
               id.setText(add1);
               String add2=rs.getString("Name");
               name.setText(add2);
               String add3=rs.getString("Surname");
               surname.setText(add3);
               String add=rs.getString("Class");
               age.setText(add);
               String adr1=rs.getString("Physics");
               physics.setText(adr1);
               String adr2=rs.getString("Maths");
               maths.setText(adr2);
               String adr3=rs.getString("Chemistry");
               chemistry.setText(adr3);
               String adr=rs.getString("IP");
               ip.setText(adr);
            }
                 
           int p=Integer.parseInt(physics.getText());
           int m=Integer.parseInt(maths.getText());
           int c=Integer.parseInt(chemistry.getText());
           int i=Integer.parseInt(ip.getText());
           float tot;
           float percentage;
           tot=p+m+c+i;
           percentage= tot/4;
           String answer;
           total.setText(String.valueOf(tot));
           answer=String.format("%.2f",percentage);
           per.setText(answer);
        }
        catch(NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_ComboBoxMousePressed

    private void ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxMouseClicked
     
    }//GEN-LAST:event_ComboBoxMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
     try{
         String sql="select * from StudentDetails where name=?";
         pst=conn.prepareStatement(sql);
         pst.setString(1,txt_search.getText());
         rs=pst.executeQuery();
         if(rs.next())
         {
             String add1=rs.getString("RollNo");
               id.setText(add1);
               String add2=rs.getString("Name");
               name.setText(add2);
               String add3=rs.getString("Surname");
               surname.setText(add3);
               String add=rs.getString("Class");
               age.setText(add);
               String adr1=rs.getString("Physics");
               physics.setText(adr1);
               String adr2=rs.getString("Maths");
               maths.setText(adr2);
               String adr3=rs.getString("Chemistry");
               chemistry.setText(adr3);
               String adr=rs.getString("IP");
               ip.setText(adr);
           int p=Integer.parseInt(physics.getText());
           int m=Integer.parseInt(maths.getText());
           int c=Integer.parseInt(chemistry.getText());
           int i=Integer.parseInt(ip.getText());
           float tot;
           float percentage;
           tot=p+m+c+i;
           percentage= tot/4;
           String answer;
           total.setText(String.valueOf(tot));
           answer=String.format("%.2f",percentage);
           per.setText(answer);
         }

     }
        catch(NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

     try{
         String sql="select * from StudentDetails where RollNo=?";
         pst=conn.prepareStatement(sql);
         pst.setString(1,txt_search.getText());
         rs=pst.executeQuery();
         if(rs.next())
         {
             String add1=rs.getString("RollNo");
               id.setText(add1);
               String add2=rs.getString("Name");
               name.setText(add2);
               String add3=rs.getString("Surname");
               surname.setText(add3);
               String add=rs.getString("Class");
               age.setText(add);
               String adr1=rs.getString("Physics");
               physics.setText(adr1);
               String adr2=rs.getString("Maths");
               maths.setText(adr2);
               String adr3=rs.getString("Chemistry");
               chemistry.setText(adr3);
               String adr=rs.getString("IP");
               ip.setText(adr);
          
           int p=Integer.parseInt(physics.getText());
           int m=Integer.parseInt(maths.getText());
           int c=Integer.parseInt(chemistry.getText());
           int i=Integer.parseInt(ip.getText());
           float tot;
           float percentage;
           tot=p+m+c+i;
           percentage= tot/4;
           String answer;
           total.setText(String.valueOf(tot));
           answer=String.format("%.2f",percentage);
           per.setText(answer);
         }

     }
        catch(NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
     
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
       try{
           Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"D:\\Overview.pdf");
       }
       catch(IOException e){
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perActionPerformed

    private void TableemployeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableemployeeKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_UP){
            try
            {
                int row=Tableemployee.getSelectedRow();
                String Tableclick=(Tableemployee.getModel().getValueAt(row,0).toString());
                String sql="select * from StudentDetails where RollNo = '"+Tableclick+"' ";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next())
                {
                    String add1=rs.getString("RollNo");
                    id.setText(add1);
                    String add2=rs.getString("Name");
                    name.setText(add2);
                    String add3=rs.getString("Surname");
                    surname.setText(add3);
                    String add=rs.getString("Class");
                    age.setText(add);
                    String adr1=rs.getString("Physics");
                    physics.setText(adr1);
                    String adr2=rs.getString("Maths");
                    maths.setText(adr2);
                    String adr3=rs.getString("Chemistry");
                    chemistry.setText(adr3);
                    String adr=rs.getString("IP");
                    ip.setText(adr);
                }
                int p=Integer.parseInt(physics.getText());
                int m=Integer.parseInt(maths.getText());
                int c=Integer.parseInt(chemistry.getText());
                int i=Integer.parseInt(ip.getText());
                float tot;
                float percentage;
                tot=p+m+c+i;
                percentage= tot/4;
                String answer;
                total.setText(String.valueOf(tot));
                answer=String.format("%.2f",percentage);
                per.setText(answer);

                String sq="update StudentDetails set Total='"+total.getText()+"',Percentage= '"+per.getText()+"' where RollNo= '"+Tableclick+"' ";
                pst=conn.prepareStatement(sq);
                pst.execute();

            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);

            }

        }
    }//GEN-LAST:event_TableemployeeKeyPressed

    private void TableemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableemployeeMouseClicked
        try
        {
            int row=Tableemployee.getSelectedRow();
            String Tableclick=(Tableemployee.getModel().getValueAt(row,0).toString());
            String sql="select * from StudentDetails where RollNo = '"+Tableclick+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("RollNo");
                id.setText(add1);
                String add2=rs.getString("Name");
                name.setText(add2);
                String add3=rs.getString("Surname");
                surname.setText(add3);
                String add=rs.getString("Class");
                age.setText(add);
                String adr1=rs.getString("Physics");
                physics.setText(adr1);
                String adr2=rs.getString("Maths");
                maths.setText(adr2);
                String adr3=rs.getString("Chemistry");
                chemistry.setText(adr3);
                String adr=rs.getString("IP");
                ip.setText(adr);
            }
            int p=Integer.parseInt(physics.getText());
            int m=Integer.parseInt(maths.getText());
            int c=Integer.parseInt(chemistry.getText());
            int i=Integer.parseInt(ip.getText());
            float tot;
            float percentage;
            tot=p+m+c+i;
            percentage= tot/4;
            String answer;
            total.setText(String.valueOf(tot));
            answer=String.format("%.2f",percentage);
            per.setText(answer);
            if(percentage>50)
            {
                per.setBackground(Color.GREEN);
                per.setForeground(Color.BLACK);
            }
            else
            {
                per.setBackground(Color.RED);
                per.setForeground(Color.white);
            }

            String sq="update StudentDetails set Total='"+total.getText()+"',Percentage= '"+per.getText()+"' where RollNo= '"+Tableclick+"' ";
            pst=conn.prepareStatement(sq);
            pst.execute();

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);

        }
        update_table();
    }//GEN-LAST:event_TableemployeeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabletextdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabletextdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabletextdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabletextdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabletextdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JMenu Date_txt;
    private javax.swing.JTable Tableemployee;
    private javax.swing.JMenu Time_txt;
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField age;
    private javax.swing.JTextField chemistry;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id;
    private javax.swing.JTextField ip;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField maths;
    private javax.swing.JTextField name;
    private javax.swing.JTextField per;
    private javax.swing.JTextField physics;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txt_search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
}
